@hostname = {{HostAddress}}
@port = 4001
@host = {{hostname}}:{{port}}
@contentType = application/json
@routeName = user

# @name usersPage
GET {{host}}/{{routeName}}
Content-Type: {{contentType}}

###
# @name getAllUsers
GET {{host}}/{{routeName}}/all
Content-Type: {{contentType}}

###

# @name getUser
GET {{host}}/{{routeName}}/1
Content-Type: {{contentType}}