# Combined frontend + backend in single container
# ports should be removed when commiting this file.
# they will be overriden using docker-compose.override.yml
#

name: heat-loss-jsapp-combined-container
services:
  mysql:
    container_name: mysqlContainer
    image: mysql:8.0.42
    # command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    env_file:
      - ./backend/.env.container
    ports:
      - 3307:3306
    volumes:
      # - ./db/init/:/docker-entrypoint-initdb.d/
      - heatloss_js_app_mysql_data:/var/lib/mysql
      # - ./db/mysql/lib_mysql:/var/lib/mysql
    healthcheck:
      # Add this
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      # timeout: 5s
      # retries: 3

  fullstack:
    container_name: fullstackContainer
    env_file:
      - ./backend/.env.container
    build:
      context: .
      dockerfile: Dockerfile.combined
    volumes:
      - ./backend:/heatLossApp/backend
      - backend_node_modules:/heatLossApp/backend/node_modules
      - ./frontend:/heatLossApp/frontend
      - frontend_node_modules:/heatLossApp/frontend/node_modules
    ports:
      - 3000:3000
      - 4001:4001
      - 9229:9229
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  heatloss_js_app_mysql_data:
  backend_node_modules:
  frontend_node_modules:


networks:
  default:
    name: heat-loss-jsapp-network
