name: mysql-server-in-docker
services:
  mysql:
    container_name: mysqlContainer
    image: mysql:8.0.42
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    env_file: 
      - ./backend/.env
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

        

volumes:
  mysql_data: